/*
 * This source file was generated by the Gradle 'init' task
 */
package hrmanagement;

import javax.swing.SwingUtilities;

import hrmanagement.view.gui.LoginDialog;
import hrmanagement.view.gui.MainFrame;

public class App {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            LoginDialog loginDialog = new LoginDialog(null);
            loginDialog.setVisible(true);

            if (loginDialog.isSucceeded()) {
                MainFrame frame = new MainFrame();
                frame.setVisible(true);
            } else {
                System.exit(0);
            }
        });
    }
}
